//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvassDetail
    {
        public int CanvassDetailID { get; set; }
        public Nullable<int> CanvassID { get; set; }
        public Nullable<int> PurchaseRequestDetailID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Canvass Canvass { get; set; }
        public virtual PurchaseRequestDetail PurchaseRequestDetail { get; set; }
    }
}
