//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canvass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canvass()
        {
            this.CanvassDetails = new HashSet<CanvassDetail>();
        }
    
        public int CanvassID { get; set; }
        public Nullable<System.DateTime> DateCanvass { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> PurchaseRequestID { get; set; }
        public string Canvasser { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Winner { get; set; }
        public string TimeOpened { get; set; }
        public string ACTNo { get; set; }
        public string ACDNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvassDetail> CanvassDetails { get; set; }
        public virtual PurchaseRequest PurchaseRequest { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
