//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public Nullable<int> PurchaseRequestID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int UserID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual PurchaseRequest PurchaseRequest { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
