//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequest()
        {
            this.Logs = new HashSet<Log>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
            this.Canvasses = new HashSet<Canvass>();
        }
    
        public int PurchaseRequestID { get; set; }
        public string ControlNumber { get; set; }
        public string PRNumber { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> DatePRAssigned { get; set; }
        public Nullable<System.DateTime> DatePrepared { get; set; }
        public int DivisionID { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> ForRevision { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual Status Status { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canvass> Canvasses { get; set; }
    }
}
