//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequestDetail()
        {
            this.CanvassDetails = new HashSet<CanvassDetail>();
        }
    
        public int PurchaseRequestDetailID { get; set; }
        public Nullable<int> PurchaseRequestID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ItemName { get; set; }
        public string Specification { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual PurchaseRequest PurchaseRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvassDetail> CanvassDetails { get; set; }
    }
}
